import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { LandingHeader } from '../components/layout/LandingHeader'
import { LandingFooter } from '../components/layout/LandingFooter'
import PageTransition from '../components/layout/PageTransition'
import { Plus, Minus, HelpCircle, MessageCircle } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Button } from '../components/ui/button'

const faqs = [
    {
        question: "How does the plagiarism detection work?",
        answer: "Our advanced algorithm scans your text against billions of web pages and academic papers to identify potential matches. We use a combination of exact matching and semantic analysis to detect even paraphrased content."
    },
    {
        question: "Is my data check secure?",
        answer: "Yes, absolutely. We prioritize your privacy and security. Content submitted for checking is processed securely and is not stored or shared with third parties without your explicit consent."
    },
    {
        question: "What file formats do you support?",
        answer: "We support a wide range of formats including .doc, .docx, .pdf, .txt, and .rtf. You can also paste text directly into the editor for quick checks."
    },
    {
        question: "Do you detect AI-generated content?",
        answer: "Yes, our system includes a specialized AI detection module that analyzes text patterns to identify content likely generated by AI models like GPT-4, Claude, and others."
    },
    {
        question: "How do I upgrade my plan?",
        answer: "You can upgrade your plan at any time from your dashboard settings. We offer flexible tiers suitable for students, professionals, and enterprise organizations."
    },
    {
        question: "Can I use the API for my own application?",
        answer: "Yes! We offer a robust API for developers. Check out our Documentation page for integration guides and API reference."
    }
]

export default function FAQPage() {
    const [openIndex, setOpenIndex] = useState<number | null>(0)

    return (
        <div className="min-h-screen flex flex-col bg-background selection:bg-primary/20">
            <LandingHeader />
            <div className="flex-grow pt-32 pb-20">
                <PageTransition>
                    <div className="container mx-auto px-4 md:px-6 max-w-4xl">
                        <div className="text-center mb-16">
                            <motion.div
                                initial={{ opacity: 0, y: 20 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ duration: 0.5 }}
                            >
                                <div className="inline-flex items-center justify-center p-3 mb-6 bg-primary/10 rounded-2xl text-primary">
                                    <HelpCircle className="w-8 h-8" />
                                </div>
                                <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-6 bg-gradient-to-br from-foreground to-foreground/70 bg-clip-text text-transparent">
                                    Frequently Asked Questions
                                </h1>
                                <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
                                    Find answers to common questions about our platform, features, and pricing.
                                </p>
                            </motion.div>
                        </div>

                        <div className="space-y-4">
                            {faqs.map((faq, index) => (
                                <motion.div
                                    key={index}
                                    initial={{ opacity: 0, y: 20 }}
                                    animate={{ opacity: 1, y: 0 }}
                                    transition={{ duration: 0.5, delay: index * 0.1 }}
                                    className="border border-border/50 rounded-xl bg-card overflow-hidden hover:border-primary/20 transition-colors"
                                >
                                    <button
                                        onClick={() => setOpenIndex(openIndex === index ? null : index)}
                                        className="flex items-center justify-between w-full p-6 text-left"
                                    >
                                        <span className="text-lg font-medium pr-8">{faq.question}</span>
                                        <div className={`p-2 rounded-full transition-colors ${openIndex === index ? 'bg-primary/10 text-primary' : 'bg-muted text-muted-foreground'}`}>
                                            {openIndex === index ? <Minus className="w-4 h-4" /> : <Plus className="w-4 h-4" />}
                                        </div>
                                    </button>
                                    <AnimatePresence>
                                        {openIndex === index && (
                                            <motion.div
                                                initial={{ height: 0, opacity: 0 }}
                                                animate={{ height: "auto", opacity: 1 }}
                                                exit={{ height: 0, opacity: 0 }}
                                                transition={{ duration: 0.3, ease: "easeInOut" }}
                                            >
                                                <div className="px-6 pb-6 text-muted-foreground leading-relaxed">
                                                    {faq.answer}
                                                </div>
                                            </motion.div>
                                        )}
                                    </AnimatePresence>
                                </motion.div>
                            ))}
                        </div>

                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.5, delay: 0.6 }}
                            className="mt-16 p-8 rounded-2xl bg-gradient-to-br from-primary/5 to-transparent border border-primary/10 text-center"
                        >
                            <div className="inline-flex items-center justify-center p-3 mb-4 bg-background rounded-full shadow-sm">
                                <MessageCircle className="w-6 h-6 text-primary" />
                            </div>
                            <h3 className="text-2xl font-bold mb-3">Still have questions?</h3>
                            <p className="text-muted-foreground mb-8 max-w-lg mx-auto">
                                Can't find the answer you're looking for? Please chat to our friendly team.
                            </p>
                            <Link to="/contact">
                                <Button size="lg" className="h-12 px-8 text-base">
                                    Get in Touch
                                </Button>
                            </Link>
                        </motion.div>
                    </div>
                </PageTransition>
            </div>
            <LandingFooter />
        </div>
    )
}
