#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running pre-commit checks..."

# Frontend
echo "Checking Frontend..."
cd frontend
echo "Running Frontend Lint..."
npm run lint || exit 1
echo "Running Frontend Tests..."
npm run test -- --run || exit 1
cd ..

# Backend
echo "Checking Backend..."
cd backend
echo "Running Backend Lint..."
npm run lint || exit 1
echo "Running Backend Tests..."
npm run test || exit 1
cd ..

echo "All checks passed!"
