#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running pre-commit checks..."


# Frontend
echo "Checking Frontend..."
cd frontend
echo "Running Frontend Lint..."
npm run lint || exit 1
echo "Running Frontend Tests..."
TEST_FILES=$(find src -type f -name "*.test.*" -o -name "*.spec.*")
if [ -n "$TEST_FILES" ]; then
	npm run test -- --run || exit 1
else
	echo "No frontend test files found, skipping test check."
fi
cd ..

# Backend
echo "Checking Backend..."
cd backend
echo "Running Backend Lint..."
npm run lint || exit 1
echo "Running Backend Tests..."
TEST_FILES=$(find src -type f -name "*.test.*" -o -name "*.spec.*")
if [ -n "$TEST_FILES" ]; then
	npm run test || exit 1
else
	echo "No backend test files found, skipping test check."
fi
cd ..

echo "All checks passed!"
